{% set name = "atool" %}
{% set version = "0.39.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://savannah.nongnu.org/download/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aaf60095884abb872e25f8e919a8a63d0dabaeca46faeba87d12812d6efc703b

build:
  skip: true  # [win or osx]
  number: 0
  #script: set -x; set +e; ./configure --prefix=${PREFIX}; cat Makefile; echo ______________1; grep -i prefix Makefile; echo ______________2; grep PREFIX Makefile; echo ______________3; grep PREFIX Makefile | env -i PREFIX=$PREFIX $(which envsubst); echo ______________4; env -i PREFIX=$PREFIX $(which envsubst) < Makefile > Makefile2; mv Makefile2 Makefile; echo START MAKEFILE; cat Makefile; echo END MAKEFILE; grep -Hni placehold Makefile*; grep -Hni PREFIX *; python -c 'print(open("Makefile", "rb").read())'; make PREFIX=$PREFIX install
  script: ./configure --prefix=${PREFIX}; python -c 'c=open("Makefile", "rb").read(); print(c[c.find(b"DSBINDIR"):][:100]); assert b"PREFIX" in c; c = c.replace(b"$PREFIX", b"'${PREFIX}'"); open("Makefile", "wb").write(c)'; make install

requirements:
  build:
    - perl >=5.004
    - make
    - python
  run:
    - perl >=5.004

test:
  commands:
    - grep SYSCONFDIR $(which atool)
    - head -n 1 $(which atool)
    - atool --help
    - aunpack --help
    - apack --help

about:
  home: https://www.nongnu.org/atool/
  license: GPL-2.0-only
  license_file: COPYING
  summary: atool is a script for managing file archives of various types (tar, tar+gzip, zip etc).

extra:
  recipe-maintainers:
    - jonashaag
